services:
  ian-is-online:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    env_file:
      - prod.env
    environment:
      - STAGE=dev
      - DEBUG=true
    ports:
      - 5000:5000
  backend:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.backend
    env_file:
      - prod.env
    environment:
      - STAGE=dev
      - DEBUG=true
    ports:
      - 5000:5000
    volumes:
      - ./application/backend:/app/application/backend
